name: Windows 11 x64 Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest  # GitHub 默认 Windows 环境支持 64 位编译
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/Microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg install openssl:x64-windows libjpeg-turbo:x64-windows
      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" -G "Visual Studio 17 2022" -A x64
      - name: Build Release
        run: cmake --build build --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows11-x64-Binaries
          path: build/bin/Release/*.exe
